### ISSUE TITLE
Doxygen documentation of all public, user-facing methods and classes

### ISSUE THREAD

**Issue by peterwittek** [PanPalitta/phase_estimation#23]

**Comment by peterwittek** [comment]
The [documentation](https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/tree/master/doc) of Trotter-Suzuki-MPI should give you an idea what could be done. Then, for publishing the documentation and making releases, you have two options on GitHub:

1. Create a branch in the phase_estimation repository called gh-pages. Generate the HTML doxygen documentation and copy it to this branch. The documentation will automatically appear at panpalitta.github.io/phase_estimation.
2. Create an organization page and migrate the phase_estimation repository there. Let's say, the organization is called whatever. Then, within the organization page, create a repository called whatever.github.io, and copy the generated HTML documentation there as in (1). The documentation will appear at whatever.github.io. This approach is more professional, and this is what Trotter-Suzuki-MPI chose: [trotter-suzuki-mpi.github.io](https://trotter-suzuki-mpi.github.io/).

**Comment by PanPalitta** [comment]
I am in favour of the second option since it allows us to put in a nice documentation for the code. I am thinking of adding a documentation on the how the program is structured as another page. Is there anything else you think we should include?

**Comment by PanPalitta** [comment]
I have created `gh-pages` branch on the current repository and upload the documentation generated by doxygen onto the branch. I have rewritten the readme file so it compiles more to the format in trotter-suzuki-mpi.github.io so we can have some idea what the final organization page would look like. Aside from putting the correct links into the download part, I can't think of anything else to add.

**Comment by peterwittek** [comment]
You are almost there. You made some changes in the documentation in the gh-pages branch, such as deleting the eps file and a few others. Actually, these changes should be in the master branch. The gh-pages branch is special: its sole purpose is to host the *generated* documentation, that is, the html files. For instance, the index.html should be in the root folder of gh-pages. This is why [panpalitta.github.io/phase_estimation](http://panpalitta.github.io/phase_estimation) does not show anything.

**Comment by PanPalitta** [comment]
I have made the corrections, except for putting in the correct links for downloads and issue report. Actually, I have a question about the release version and the development version. Are they basically two branches?

**Comment by peterwittek** [comment]
The issues link should be this: [https://github.com/PanPalitta/phase_estimation/issues](https://github.com/PanPalitta/phase_estimation/issues)

Releases will appear here: [https://github.com/PanPalitta/phase_estimation/releases](https://github.com/PanPalitta/phase_estimation/releases)

Here is my checklist for creating a C++ release:

1. Code formatting and completeness.
  - Changelog is complete.
  - Code is formatted nicely with astyle.
  - Version number is correct in configure.ac and documentation (whatever.doxy).
  - Documentation is generated correctly.
  - make dist packages what is expected.

2. Compilation is clean under -Wall -Wextra.

3. Runs clean under Valgrind.

4. Release:
   - Tag and push tag to GitHub:
        ```
        git tag -a X.X.X -m "version X.X.X"

        git push --tags
        ```
 - Add release notes on GitHub based on Changelog.

5. Publicity: if listed in any index, make matching announcements.

**Comment by peterwittek** [comment]
In the description part of the GitHub [repo page](https://github.com/PanPalitta/phase_estimation), you could add a one-sentence summary, as well as the [link](http://panpalitta.github.io/phase_estimation) to the documentation.

**Comment by PanPalitta** [comment]
I've fixed the issues and create a version 1.0.0 release. Should we clean up the branches we have?

**Comment by peterwittek** [comment]
Yes, you can also delete the peterwittek-master branch. If I contribute, I push changes through my fork anyway. 

There is one thing left to do. Please run ``make dist``. The resulting .gz file could be uploaded to the [release](https://github.com/PanPalitta/phase_estimation/releases). Also, please edit the documentation to include the download and bug report links.

**Comment by PanPalitta** [comment]
I've updated the documents and run the make dist. However, I'm not entirely sure what to do with the .gz file. It's current in the master branch and I have no idea how to upload directly to release. However, I only realize now that Github release tool already generate a tar.gz file of the source. Do we still need the tar.gz in the branch?

**Comment by peterwittek** [comment]
Please delete the binary file from the repository -- by principle, it has no place there. When you go to the releases as admin, you can edit a release. When you do that, you are able to upload a binary file: this where the gz should go. See, for instance, [here](https://github.com/peterwittek/somoclu/releases) there is always a gz that was created by ``make dist``.

**Comment by PanPalitta** [comment]
I have done as instructed. Now I know what are needed for a release! Thank you very much for your guidance. I'm debating whether we should move this repository to an organization page now, or wait until we have some papers and references first. Please let me know what you think.

**Comment by peterwittek** [comment]
It looks perfect. From here, it takes a total of five clicks to transition to an organization page, but if and only if you think it will ever make it beyond phase estimation. If this can be the backbone of other reinforcement learning algorithms in quantum physics, then the organization page is the way to go.

**Comment by PanPalitta** [comment]
Thank you for your suggestion, Peter. Then we'll leave it like this until further development.
